SELECT MAX(age) FROM users GROUP BY age; /* GROUP BY agrupa los resultados de una consulta por un campo en particular, en este caso por edad */
SELECT MAX(age) FROM users GROUP BY age, name; /* GROUP BY agrupa los resultados de una consulta por un campo en particular, en este caso por edad y nombre */
SELECT count(age) AS 'grupos' FROM users GROUP BY age; /* GROUP BY agrupa los resultados de una consulta por un campo en particular o igual, en este caso por edad */
SELECT count(age) AS 'grupos' FROM users GROUP BY age, name; /* GROUP BY agrupa los resultados de una consulta por un campo en particular o igual, en este caso por edad y nombre */
SELECT count(age) AS 'grupos' FROM users GROUP BY age, name HAVING age > 30; /* HAVING es una clausula que se usa para filtrar los resultados de una consulta agrupada, en este caso por edad y nombre */
SELECT count(age) AS 'grupos' FROM users GROUP BY age, name HAVING age > 30 AND name = 'Myriam'; /* HAVING es una clausula que se usa para filtrar los resultados de una consulta agrupada, en este caso por edad y nombre */
SELECT count(age) AS 'grupos' FROM users GROUP BY age, name HAVING age > 30 OR name = 'Myriam'; /* HAVING es una clausula que se usa para filtrar los resultados de una consulta agrupada, en este caso por edad y nombre */
SELECT count(age) AS 'grupos' FROM users GROUP BY age, name HAVING age > 30 AND name = 'Myriam' OR name = 'Jorge'; /* HAVING es una clausula que se usa para filtrar los resultados de una consulta agrupada, en este caso por edad y nombre */
SELECT count(age) AS 'grupos' FROM users GROUP BY age, name HAVING age > 30 OR name = 'Myriam' OR name = 'Jorge'; /* HAVING es una clausula que se usa para filtrar los resultados de una consulta agrupada, en este caso por edad y nombre */
SELECT count(age) AS 'grupos' FROM users GROUP BY age, name HAVING age > 30 AND name = 'Myriam' OR name = 'Jorge'; /* HAVING es una clausula que se usa para filtrar los resultados de una consulta agrupada, en este caso por edad y nombre */
SELECT COUNT(age) AS 'grupos' FROM users WHERE age >15 GROUP BY age ORDER BY age ASC; /* ORDER BY ordena los resultados de una consulta por un campo en particular, en este caso por edad */
SELECT COUNT(age) AS 'grupos' FROM users WHERE age >15 GROUP BY age ORDER BY age DESC; /* ORDER BY ordena los resultados de una consulta por un campo en particular, en este caso por edad */
SELECT COUNT(age) AS 'grupos' FROM users WHERE age >15 GROUP BY age ORDER BY age ASC LIMIT 5; /* LIMIT limita el numero de resultados de una consulta, en este caso a 5 */
SELECT COUNT(age) AS 'grupos' FROM users WHERE age >15 GROUP BY age ORDER BY age DESC LIMIT 5; /* LIMIT limita el numero de resultados de una consulta, en este caso a 5 */ 
SELECT COUNT(age) AS 'grupos' FROM users WHERE age >15 GROUP BY age ORDER BY age ASC LIMIT 5 OFFSET 5; /* OFFSET es una clausula que se usa para saltar un numero de resultados de una consulta, en este caso 5 */
SELECT COUNT(age) AS 'grupos' FROM users WHERE age >15 GROUP BY age ORDER BY age DESC LIMIT 5 OFFSET 5; /* OFFSET es una clausula que se usa para saltar un numero de resultados de una consulta, en este caso 5 */
SELECT COUNT(age) AS 'grupos' FROM users WHERE age >15 GROUP BY age ORDER BY age ASC LIMIT 5 OFFSET 5; /* OFFSET es una clausula que se usa para saltar un numero de resultados de una consulta, en este caso 5 */
SELECT COUNT(age) AS 'grupos' FROM users WHERE age >15 GROUP BY age ORDER BY age DESC LIMIT 5 OFFSET 5; /* OFFSET es una clausula que se usa para saltar un numero de resultados de una consulta, en este caso 5 */
SELECT COUNT(age) AS 'grupos' FROM users WHERE age >15 GROUP BY age ORDER BY age ASC LIMIT 5 OFFSET 5; /* OFFSET es una clausula que se usa para saltar un numero de resultados de una consulta, en este caso 5 */
SELECT COUNT(age) AS 'grupos' FROM users WHERE age >15 GROUP BY age ORDER BY age DESC LIMIT 5 OFFSET 5; /* OFFSET es una clausula que se usa para saltar un numero de resultados de una consulta, en este caso 5 */
SELECT COUNT(age) AS 'grupos' FROM users WHERE age >15 GROUP BY age ORDER BY age ASC LIMIT 5 OFFSET 5; /* OFFSET es una clausula que se usa para saltar un numero de resultados de una consulta, en este caso 5 */
SELECT COUNT(age) AS 'grupos' FROM users WHERE age >15 GROUP BY age ORDER BY age DESC LIMIT 5 OFFSET 5; /* OFFSET es una clausula que se usa para saltar un numero de resultados de una consulta, en este caso 5 */
SELECT COUNT(age) AS 'grupos' FROM users WHERE age >15 GROUP BY age ORDER BY age ASC LIMIT 5 OFFSET 5; /* OFFSET es una clausula que se usa para saltar un numero de resultados de una consulta, en este caso 5 */
SELECT COUNT(age) AS 'grupos' FROM users WHERE age >15 GROUP BY age ORDER BY age DESC LIMIT 5 OFFSET 5; /* OFFSET es una clausula que se usa para saltar un numero de resultados de una consulta, en este caso 5 */
SELECT COUNT(age) AS 'grupos' FROM users WHERE age >15 GROUP BY age ORDER BY age ASC LIMIT 5 OFFSET 5; /* OFFSET es una clausula que se usa para saltar un numero de resultados de una consulta, en este caso 5 */
SELECT COUNT(age) AS 'grupos' FROM users WHERE age >15 GROUP BY age ORDER BY age DESC LIMIT 5 OFFSET 5; /* OFFSET es una clausula que se usa para saltar un numero de resultados de una consulta, en este caso 5 */
SELECT COUNT(age) AS 'grupos' FROM users WHERE age >15 GROUP BY age ORDER BY age ASC LIMIT 5 OFFSET 5; /* OFFSET es una clausula que se usa para saltar un numero de resultados de una consulta, en este caso 5 */
SELECT COUNT(age) AS 'grupos' FROM users WHERE age >15 GROUP BY age ORDER BY age DESC LIMIT 5 OFFSET 5; /* OFFSET es una clausula que se usa para saltar un numero de resultados de una consulta, en este caso 5 */
SELECT COUNT(age) AS 'grupos' FROM users WHERE age >15 GROUP BY age ORDER BY age ASC LIMIT 5 OFFSET 5; /* OFFSET es una clausula que se usa para saltar un numero de resultados de una consulta, en este caso 5 */
SELECT COUNT(age) AS 'grupos' FROM users WHERE age >15 GROUP BY age ORDER BY age DESC LIMIT 5 OFFSET 5; /* OFFSET es una clausula que se usa para saltar un numero de resultados de una consulta, en este caso 5 */
SELECT COUNT(age) AS 'grupos' FROM users WHERE age >15 GROUP BY age ORDER BY age ASC LIMIT 5 OFFSET 5; /* OFFSET es una clausula que se usa para saltar un numero de resultados de una consulta, en este caso 5 */
SELECT COUNT(age) AS 'grupos' FROM users WHERE age >15 GROUP BY age ORDER BY age DESC LIMIT 5 OFFSET 5; /* OFFSET es una clausula que se usa para saltar un numero de resultados de una consulta, en este caso 5 */
SELECT COUNT(age) AS 'grupos' FROM users WHERE age >15 GROUP BY age ORDER BY age ASC LIMIT 5 OFFSET 5; /* OFFSET es una clausula que se usa para saltar un numero de resultados de una consulta, en este caso 5 */
SELECT COUNT(age) AS 'grupos' FROM users WHERE age >15 GROUP BY age ORDER BY age DESC LIMIT 5 OFFSET 5; /* OFFSET es una clausula que se usa para saltar un numero de resultados de una consulta, en este caso 5 */
SELECT COUNT(age) AS 'grupos' FROM users WHERE age >15 GROUP BY age ORDER BY age ASC LIMIT 5 OFFSET 5; /* OFFSET es una clausula que se usa para saltar un numero de resultados de una consulta, en este caso 5 */
SELECT COUNT(age) AS 'grupos' FROM users WHERE age >15 GROUP BY age ORDER BY age DESC LIMIT 5 OFFSET 5; /* OFFSET es una clausula que se usa para saltar un numero de resultados de una consulta, en este caso 5 */
SELECT COUNT(age) AS 'grupos' FROM users WHERE age >15 GROUP BY age ORDER BY age ASC LIMIT 5 OFFSET 5; /* OFFSET es una clausula que se usa para saltar un numero de resultados de una consulta, en este caso 5 */
SELECT COUNT(age) AS 'grupos' FROM users WHERE age >15 GROUP BY age ORDER BY age DESC LIMIT 5 OFFSET 5; /* OFFSET es una clausula que se usa para saltar un numero de resultados de una consulta, en este caso 5 */
SELECT COUNT(age) AS 'grupos' FROM users WHERE age >15 GROUP BY age ORDER BY age ASC LIMIT 5 OFFSET 5; /* OFFSET es una clausula que se usa para saltar un numero de resultados de una consulta, en este caso 5 */
SELECT COUNT(age) AS 'grupos' FROM users WHERE age >15 GROUP BY age ORDER BY age DESC LIMIT 5 OFFSET 5; /* OFFSET es una clausula que se usa para saltar un numero de resultados de una consulta, en este caso 5 */
SELECT COUNT(age) AS 'grupos' FROM users WHERE age >15 GROUP BY age ORDER BY age ASC LIMIT 5 OFFSET 5; /* OFFSET es una clausula que se usa para saltar un numero de resultados de una consulta, en este caso 5 */
SELECT COUNT(age) AS 'grupos' FROM users WHERE age >15 GROUP BY age ORDER BY age DESC LIMIT 5 OFFSET 5; /* OFFSET es una clausula que se usa para saltar un numero de resultados de una consulta, en este caso 5 */
SELECT COUNT(age) AS 'grupos' FROM users WHERE age >15 GROUP BY age ORDER BY age ASC LIMIT 5 OFFSET 5; /* OFFSET es una clausula que se usa para saltar un numero de resultados de una consulta, en este caso 5 */
SELECT COUNT(age) AS 'grupos' FROM users WHERE age >15 GROUP BY age ORDER BY age DESC LIMIT 5 OFFSET 5; /* OFFSET es una clausula que se usa para saltar un numero de resultados de una consulta, en este caso 5 */
SELECT COUNT(age) AS 'grupos' FROM users WHERE age >15 GROUP BY age ORDER BY age ASC LIMIT 5 OFFSET 5; /* OFFSET es una clausula que se usa para saltar un numero de resultados de una consulta, en este caso 5 */
SELECT COUNT(age) AS 'grupos' FROM users WHERE age >15 GROUP BY age ORDER BY age DESC LIMIT 5 OFFSET 5; /* OFFSET es una clausula que se usa para saltar un numero de resultados de una consulta, en este caso 5 */
SELECT COUNT(age) AS 'grupos' FROM users WHERE age >15 GROUP BY age ORDER BY age ASC LIMIT 5 OFFSET 5; /* OFFSET es una clausula que se usa para saltar un numero de resultados de una consulta, en este caso 5 */
SELECT COUNT(age) AS 'grupos' FROM users WHERE age >15 GROUP BY age ORDER BY age DESC LIMIT 5 OFFSET 5; /* OFFSET es una clausula que se usa para saltar un numero de resultados de una consulta, en este caso 5 */
SELECT COUNT(age) AS 'grupos' FROM users WHERE age >15 GROUP BY age ORDER BY age ASC LIMIT 5 OFFSET 5; /* OFFSET es una clausula que se usa para saltar un numero de resultados de una consulta, en este caso 5 */
SELECT COUNT(age) AS 'grupos' FROM users WHERE age >15 GROUP BY age ORDER BY age DESC LIMIT 5 OFFSET 5; /* OFFSET es una clausula que se usa para saltar un numero de resultados de una consulta, en este caso 5 */
SELECT COUNT(age) AS 'grupos' FROM users WHERE age >15 GROUP BY age ORDER BY age ASC LIMIT 5 OFFSET 5; /* OFFSET es una clausula que se usa para saltar un numero de resultados de una consulta, en este caso 5 */
SELECT COUNT(age) AS 'grupos' FROM users WHERE age >15 GROUP BY age ORDER BY age DESC LIMIT 5 OFFSET 5; /* OFFSET es una clausula que se usa para saltar un numero de resultados de una consulta, en este caso 5 */
SELECT COUNT(age) AS 'grupos' FROM users WHERE age >15 GROUP BY age ORDER BY age ASC LIMIT 5 OFFSET 5; /* OFFSET es una clausula que se usa para saltar un numero de resultados de una consulta, en este caso 5 */
SELECT COUNT(age) AS 'grupos' FROM users WHERE age >15 GROUP BY age ORDER BY age DESC LIMIT 5 OFFSET 5; /* OFFSET es una clausula que se usa para saltar un numero de resultados de una consulta, en este caso 5 */
SELECT COUNT(age) AS 'grupos' FROM users WHERE age >15 GROUP BY age ORDER BY age ASC LIMIT 5 OFFSET 5; /* OFFSET es una clausula que se usa para saltar un numero de resultados de una consulta, en este caso 5 */
SELECT COUNT(age) AS 'grupos' FROM users WHERE age >15 GROUP BY age ORDER BY age DESC LIMIT 5 OFFSET 5; /* OFFSET es una clausula que se usa para saltar un numero de resultados de una consulta, en este caso 5 */
SELECT COUNT(age) AS 'grupos' FROM users WHERE age >15 GROUP BY age ORDER BY age ASC LIMIT 5 OFFSET 5; /* OFFSET es una clausula que se usa para saltar un numero de resultados de una consulta, en este caso 5 */
SELECT COUNT(age) AS 'grupos' FROM users WHERE age >15 GROUP BY age ORDER BY age DESC LIMIT 5 OFFSET 5; /* OFFSET es una clausula que se usa para saltar un numero de resultados de una consulta, en este caso 5 */